Repository iabacus2024dev/frontend, pull requests merged in 2025-04, with the labels that each got.

#140 [REQ-04-08][FUN-036] 구성원 퇴사처리
  src/apis/employeeService.js
  src/components/common/DialogComponent.vue
  src/components/employee/PersonalContractInfoComponent.vue
  src/views/employee/EmployeeCreatePopup.vue
  src/views/employee/EmployeeDetailPage.vue
Labels: ✨ Feature

#143 [COMMON] 검색바컴포넌트 드롭다운 기본 선택 변경
  src/components/project/BasicInfoComponent.vue
  src/components/searchbar/SearchBarComponent.vue
  src/views/project/ProjectDetailPage.vue
  src/views/project/ProjectPage.vue
Labels: ✨ Feature

#145 구성원 팀 검색 구현
  src/components/common/MainHeaderComponent.vue
  src/components/employee/CommentComponent.vue
  src/components/employee/PersonalContractInfoComponent.vue
  src/components/employee/PersonalInfoComponent.vue
  src/components/employee/PersonalRecordComponent.vue
  src/components/partners/AdditionalInfoComponent.vue
  src/components/partners/ContractInfoComponent.vue
  src/components/partners/PartnersInfoComponent.vue
  src/components/project/BasicInfoComponent.vue
  src/components/searchbar/SearchBarComponent.vue
  src/components/table/TableEventComponent.vue
  src/views/employee/EmployeeCreatePopup.vue
  src/views/employee/EmployeePage.vue
  src/views/project/ContractDetailPage.vue
  src/views/project/ProjectDetailPage.vue
Labels: ✨ Feature

#146 bugfix: 프로젝트 생성 및 팀 조회 수정
  src/components/partners/PartnersInfoComponent.vue
  src/components/project/BasicInfoComponent.vue
  src/views/employee/EmployeeCreatePopup.vue
  src/views/employee/EmployeePage.vue
  src/views/project/ProjectCreatePopup.vue
  src/views/project/ProjectDetailPage.vue
Labels: 🐞 BugFix

#151 [REQ-08-02][FUN-077] 매출관리 메인화면
  src/apis/salesService.js
  src/components/common/ExcelActionsComponent.vue
  src/views/SalesPage.vue
Labels: ✨ Feature

#152 feature: 연도 입력 구현
  src/components/searchbar/SearchBarComponent.vue
Labels: ✨ Feature

#153 refactor: 마이페이지 UI 개선 및 기능 확장
  src/apis/memberService.js
  src/apis/projectService.js
  src/components/profile/BasicProfileComponent.vue
  src/components/profile/DeleteMemberComponent.vue
  src/components/profile/PasswordChangeComponent.vue
  src/components/profile/ProjectListComponent.vue
  src/components/profile/RoleListComponent.vue
  src/views/ProfilePage.vue
Labels: ✨ Feature, 🔨 Refactor

#154 refactor: HeaderComponent UI 및 동작 개선
  src/components/common/HeaderComponent.vue
Labels: 🔨 Refactor

#155 feature: 금액, 전화번호 처리 유틸리티 도입 및 관련 로직 통합
  src/components/common/HeaderComponent.vue
  src/components/employee/PersonalContractInfoComponent.vue
  src/components/employee/PersonalInfoComponent.vue
  src/components/partners/PartnersInfoComponent.vue
  src/components/profile/BasicProfileComponent.vue
  src/components/profile/ProjectListComponent.vue
  src/components/profile/RoleListComponent.vue
  src/components/project/AmountComponent.vue
  src/components/project/BasicInfoComponent.vue
  src/components/project/ClientCompanyComponent.vue
  src/components/project/MainCompanyComponent.vue
  src/utils/MoneyUtils.js
  src/utils/PhoneUtils.js
  src/views/SalesPage.vue
  src/views/employee/EmployeeSalaryPage.vue
  src/views/partners/PartnersPage.vue
  src/views/project/ProjectPage.vue
Labels: ✨ Feature, 🔨 Refactor

#156 feat: 프론트엔드 입력 폼 유효성 검사 및 필수 입력 항목 추가
  src/components/common/DialogComponent.vue
  src/components/employee/PersonalContractInfoComponent.vue
  src/components/employee/PersonalInfoComponent.vue
  src/components/employee/PersonalRecordComponent.vue
  src/components/partners/PartnersInfoComponent.vue
  src/components/profile/RoleListComponent.vue
  src/components/project/AmountComponent.vue
  src/components/project/BasicInfoComponent.vue
  src/components/project/ClientCompanyComponent.vue
  src/components/project/MainCompanyComponent.vue
  src/components/project/ProgressInfoComponent.vue
  src/views/employee/EmployeeCreatePopup.vue
  src/views/employee/EmployeeDetailPage.vue
  src/views/employee/EmployeePage.vue
  src/views/partners/PartnersCreatePopup.vue
  src/views/partners/PartnersDetailPage.vue
  src/views/partners/PartnersPage.vue
  src/views/project/ProjectCreatePopup.vue
  src/views/project/ProjectDetailPage.vue
  src/views/project/ProjectPage.vue
Labels: ✨ Feature

#158 feature: 매출 관리 화면 구현
  src/views/SalesPage.vue
Labels: ✨ Feature

#160 feature: TableComponent footer 숨김 설정
  src/apis/salesService.js
  src/components/table/TableComponent.vue
Labels: ✨ Feature

#161 feature: SearchBar 초기화 시 재생성하여 초기화
  src/views/SalesPage.vue
  src/views/employee/EmployeePage.vue
  src/views/project/ProjectPage.vue
Labels: ✨ Feature

#164 로고 수정
  src/assets/ABACUS_CI_1.png
  src/components/common/HeaderComponent.vue
  src/views/HomePage.vue
Labels: 🪄 Fix

#165 스타일 수정 및 색상 변경
  src/components/common/DialogComponent.vue
  src/components/common/ExcelActionsComponent.vue
  src/components/common/HeaderComponent.vue
  src/components/common/ToolTipComponent.vue
  src/components/profile/BasicProfileComponent.vue
  src/components/profile/PasswordChangeComponent.vue
  src/components/profile/RoleListComponent.vue
  src/plugins/vuetify.js
  src/views/HomePage.vue
  src/views/employee/EmployeeDetailPage.vue
  src/views/partners/PartnersDetailPage.vue
  src/views/project/ProjectDetailPage.vue
Labels: 🪄 Fix

#166 feature: 글로벌 폰트 변경 - Pretendard
  src/assets/styles.css
  src/main.js
Labels: ✨ Feature, 🪄 Fix

#168 refactor: 검색 및 팀 필터링 로직 개선
  src/views/employee/EmployeePage.vue
Labels: 🐞 BugFix

#169 fix: 부서 범위 -> 부서 이름
  src/views/SalesPage.vue
Labels: 🐞 BugFix
