Repository iabacus2024dev/frontend, pull requests merged in 2025-03, with the labels that each got.

#97 [REQ-04-01][FUN-025] 구성원 관리 메인 화면 트리뷰 api 연동
  src/components/tree/LazyTreeViewWrapper.vue
  src/views/member/MemberPage.vue
Labels: ✨ Feature

#105 [REQ-05-01][FUN-039] 협력사 API 연동 및 로그인 구현
  package-lock.json
  package.json
  src/adapters/restApiAdapter.js
  src/apis/authService.js
  src/apis/employeeService.js
  src/apis/memberService.js
  src/apis/partnerService.js
  src/components/common/HeaderComponent.vue
  src/components/common/PaginationComponent.vue
  src/components/login/LoginComponent.vue
  src/components/partners/AdditionalInfoComponent.vue
  src/components/partners/ContractInfoComponent.vue
  src/components/partners/PartnersInfoComponent.vue
  src/components/profile/BasicProfileComponent.vue
  src/components/profile/DeleteMemberComponent.vue
  src/components/profile/PasswordChangeComponent.vue
  src/components/profile/ProjectListComponent.vue
  src/components/profile/TeamListComponent.vue
  src/components/searchbar/SearchBarComponent.vue
  src/components/table/TableComponent.vue
  src/main.js
  src/router/index.js
  src/stores/user.js
  src/views/login/FindPasswordPage.vue
  src/views/login/InitializePage.vue
  src/views/login/LoginPage.vue
  src/views/login/RegisterPage.vue
  src/views/partners/PartnersDetailPage.vue
  src/views/partners/PartnersPage.vue
Labels: ✨ Feature

#106 [COMMON] 로그인 수정 및 페이징 수정
  src/stores/user.js
  src/views/partners/PartnersDetailPage.vue
  src/views/partners/PartnersPage.vue
Labels: 🔨 Refactor

#115 [REQ-10-01][FUN-089] 엑셀 업로드, 다운로드 기능
  package-lock.json
  package.json
  src/adapters/restApiAdapter.js
  src/apis/common/downloadService.js
  src/apis/partnerService.js
  src/plugins/vuetify.js
  src/views/partners/PartnersPage.vue
Labels: ✨ Feature

#116 feature: 로그인 및 권한 로직 수정
  src/adapters/restApiAdapter.js
  src/apis/authService.js
  src/apis/roleService.js
  src/components/common/HeaderComponent.vue
  src/components/profile/RoleListComponent.vue
  src/main.js
  src/router/index.js
  src/stores/member.js
Labels: ✨ Feature

#117 [REQ-10-01][FUN-089]협력사 엑셀 화면 수정 및 토스트 메시지 수정
  src/components/common/ExcelActionsComponent.vue
  src/components/partners/PartnersInfoComponent.vue
  src/components/table/TableComponent.vue
  src/views/partners/PartnersDetailPage.vue
  src/views/partners/PartnersPage.vue
Labels: ✨ Feature

#118 [COMMON] 로그인 쿠키 수정
  src/adapters/restApiAdapter.js
  src/stores/member.js
Labels: 🪄 Fix

#120 [COMMON] 조직도 컴포넌트 구현
  src/apis/teamService.js
  src/components/OrganizationChartComponent.vue
  src/views/PermissionPage.vue
Labels: ✨ Feature

#121 [COMMON] 조직도 컴포넌트 수정
  src/components/OrganizationChartComponent.vue
  src/plugins/vuetify.js
Labels: 🪄 Fix

#122 [REQ-03-05][FUN-018] 권한 관리 메인 화면
  src/apis/roleService.js
  src/components/OrganizationChartComponent.vue
  src/components/common/ExcelActionsComponent.vue
  src/components/common/HeaderComponent.vue
  src/components/common/MainHeaderComponent.vue
  src/components/common/PaginationComponent.vue
  src/components/profile/BasicProfileComponent.vue
  src/components/profile/DeleteMemberComponent.vue
  src/components/profile/PasswordChangeComponent.vue
  src/components/profile/ProjectListComponent.vue
  src/components/profile/RoleListComponent.vue
  src/components/searchbar/SearchBarComponent.vue
  src/views/PermissionPage.vue
  src/views/partners/PartnersPage.vue
Labels: ✨ Feature, 🪄 Fix, 🔨 Refactor

#123 [REQ-03-05][FUN-018] 권한 관리
  src/components/common/DialogComponent.vue
  src/components/common/HeaderComponent.vue
  src/components/permission/ManagementComponent.vue
  src/components/permission/PermissionSettingComponent.vue
  src/components/permission/RoleAddComponent.vue
  src/components/permission/RoleSelectionComponent.vue
  src/components/permission/RoleSettingDialog.vue
  src/components/permission/RoleTargetComponent.vue
  src/stores/dialogStore.js
  src/views/PermissionPage.vue
Labels: ✨ Feature

#125 Fix/permissions
  src/components/common/DialogComponent.vue
  src/components/permission/RoleSettingDialog.vue
  src/components/permission/RoleTargetComponent.vue
  src/stores/roleStore.js
Labels: 🐞 BugFix

#126 feat: permission
  src/components/common/DialogComponent.vue
  src/components/permission/ManagementComponent.vue
  src/components/permission/RoleAddComponent.vue
  src/components/permission/RoleSelectionComponent.vue
  src/components/permission/RoleTargetComponent.vue
  src/views/PermissionPage.vue
Labels: ✨ Feature

#127 [REQ-05-01][FUN-039] 협력사 페이지 수정
  src/apis/partnerService.js
  src/components/table/TableComponent.vue
  src/views/partners/PartnersPage.vue
Labels: 🪄 Fix

#130 [REQ-05-02][FUN-041] 협력사 상세화면 백엔드 연동
  src/apis/projectService.js
  src/components/employee/EmployeeListComponent.vue
  src/components/project/AmountComponent.vue
  src/components/project/BasicInfoComponent.vue
  src/components/project/MainCompanyComponent.vue
  src/components/project/OrderdingCompanyComponent.vue
  src/components/project/ProgressInfoComponent.vue
  src/utils/MoneyUtils.js
  src/views/partners/PartnersPage.vue
  src/views/project/ProjectDetailPage.vue
  src/views/project/ProjectPage.vue
Labels: ✨ Feature

#131 [REQ-05-02][FUN-041] 프로젝트 검색 수정
  src/views/partners/PartnersPage.vue
  src/views/project/ProjectPage.vue
Labels: 🪄 Fix

#132 feat: permission
  src/apis/roleService.js
  src/components/permission/ManagementComponent.vue
  src/components/permission/PermissionSettingComponent.vue
  src/components/permission/RoleSettingDialog.vue
  src/router/index.js
  src/views/PermissionPage.vue
Labels: ✨ Feature

#134 [REQ-05-03][FUN-043] 협력사 등록 팝업 화면
  src/components/common/CreateDialogComponent.vue
  src/components/common/DialogComponent.vue
  src/components/partners/PartnersInfoComponent.vue
  src/views/partners/PartnersCreatePopup.vue
  src/views/partners/PartnersPage.vue
Labels: ✨ Feature

#135 feature: 협력사 등록 화면 수정
  src/App.vue
  src/components/common/DialogComponent.vue
  src/composables/useDialog.js
  src/stores/dialogStore.js
Labels: 🪄 Fix

#137 [REQ-06-03][FUN-053] 프로젝트 등록 팝업 화면
  src/apis/projectService.js
  src/components/project/AmountComponent.vue
  src/components/project/BasicInfoComponent.vue
  src/components/project/ClientCompanyComponent.vue
  src/components/project/MainCompanyComponent.vue
  src/components/project/ProjectInfoComponent.vue
  src/views/member/MemberPage.vue
  src/views/partners/PartnersCreatePopup.vue
  src/views/partners/PartnersPage.vue
  src/views/project/ProjectCreatePopup.vue
  src/views/project/ProjectDetailPage.vue
  src/views/project/ProjectPage.vue
Labels: ✨ Feature
