Repository iabacus2024dev/frontend, pull requests merged in 2025-02, with the labels that each got.

#6 [COMMON] gitignore 수정 및 .vscode 삭제
  .gitignore
  .vscode/extensions.json
Labels: ⚙ Setting

#7 [COMMON] axios 설치
  package-lock.json
  package.json
Labels: ⚙ Setting

#10 [COMMON] 테이블 컴포넌트
  src/components/table/TableComponent.vue
  src/router/index.js
  src/views/HomeView.vue
  src/views/TableTestPage.vue
Labels: ✨ Feature

#11 [COMMON] 테이블 관련 이벤트 컴포넌트화
  src/components/table/TableComponent.vue
  src/components/table/TableEventComponent.vue
  src/views/TableTestPage.vue
Labels: ✨ Feature

#13 [COMMON] 테이블 컴포넌트 스타일 추가
  src/components/table/TableComponent.vue
  src/components/table/TableEventComponent.vue
Labels: ✨ Feature

#19 [COMMON] 헤더 컴포넌트 생성 및 기본 페이지 추가
  src/App.vue
  src/components/Header.vue
  src/components/common/FooterComponent.vue
  src/components/common/HeaderComponent.vue
  src/layouts/DefaultLayout.vue
  src/layouts/register.js
  src/main.js
  src/router/index.js
  src/views/HomePage.vue
  src/views/HomeView.vue
  src/views/MemberPage.vue
  src/views/PartnersPage.vue
  src/views/PermissionPage.vue
  src/views/ProfilePage.vue
  src/views/ProjectPage.vue
  src/views/SalesPage.vue
Labels: ✨ Feature

#27 [COMMON] 검색 바 컴포넌트
  src/components/searchbar/SearchBarComponent.vue
  src/router/index.js
  src/views/SearchBarTestPage.vue
Labels: ✨ Feature

#31 [COMMON] 모달 팝업 컴포넌트
  src/components/common/ModalPopupComponent.vue
  src/views/PartnersPage.vue
Labels: ✨ Feature

#28 [COMMON] 로딩 창 컴포넌트
  src/components/common/ProgressBarComponent.vue
  src/components/common/ToolTipComponent.vue
  src/router/index.js
Labels: ✨ Feature

#33 [COMMON] 페이지 네비게이션 컴포넌트
  .gitignore
  src/apis/dummy.txt
  src/apis/memberService.js
  src/components/common/PaginationComponent.vue
  src/plugins/vuetify.js
Labels: ✨ Feature

#36 [COMMON] 헤더 컴포넌트 구현
  src/components/common/HeaderComponent.vue
  src/layouts/DefaultLayout.vue
Labels: ✨ Feature

#40 [COMMON] 조직도 선택 트랜스퍼 리스트 컴포넌트화
  package-lock.json
  package.json
  src/components/common/TransferListComponent.vue
  src/components/common/memberData.js
  src/plugins/vuetify.js
  src/router/index.js
  src/views/ContractDetailPage.vue
  src/views/TransferListTestPage.vue
Labels: ✨ Feature

#43 [COMMON] 트랜스퍼 리스트 수정
  src/router/index.js
Labels: 🗑️ Delete

#44 [COMMON] 메인 헤더 컴포넌트 및 breadcrumbs 구현
  src/components/common/HeaderComponent.vue
  src/components/common/MainHeaderComponent.vue
  src/components/common/PaginationComponent.vue
  src/layouts/DefaultLayout.vue
  src/router/index.js
  src/views/HomePage.vue
  src/views/MemberPage.vue
  src/views/PartnersPage.vue
  src/views/PermissionPage.vue
  src/views/ProfilePage.vue
  src/views/ProjectPage.vue
  src/views/SalesPage.vue
Labels: ✨ Feature

#37 [COMMON] 툴팁 수정
  src/components/common/ToolTipComponent.vue
  src/components/tree/TreeView.vue
  src/router/index.js
  src/views/ToolTipTestPage.vue
Labels: ✨ Feature

#51 [REQ-07-02][FUN-060] 계약 상세 메인 화면
  src/components/project/ContractInfoComponent.vue
  src/components/project/ProgressInfoComponent.vue
  src/components/project/ProjectInfoComponent.vue
  src/components/table/TableEventComponent.vue
  src/plugins/vuetify.js
  src/router/index.js
  src/views/ContractDetailPage.vue
  src/views/project/ContractDetailPage.vue
  src/views/project/ProjectPage.vue
Labels: ✨ Feature

#50 [COMMON] 검색 바 컴포넌트 수정
  src/components/searchbar/SearchBarComponent.vue
  src/views/SearchBarTestPage.vue
Labels: 🪄 Fix

#57 [REQ-04-01][FUN-025] 구성원 관리 메인 화면
  src/views/MemberPage.vue
Labels: ✨ Feature

#60 [REQ-02-01][FUN-003] 회원 등록 메인 화면
  src/adapters/restApiAdapter.js
  src/apis/authService.js
  src/components/common/HeaderComponent.vue
  src/layouts/DefaultLayout.vue
  src/layouts/LoginLayout.vue
  src/router/index.js
  src/views/login/RegisterPage.vue
Labels: ✨ Feature

#62 [REQ-02-03][FUN-006] 비밀번호 초기화 페이지 및 로그인 페이지(임시) 구현
  src/views/login/InitializePage.vue
  src/views/login/LoginPage.vue
Labels: ✨ Feature

#63 [REQ-05-01][FUN-039]협력사 관리 메인화면
  src/layouts/DefaultLayout.vue
  src/views/PartnersPage.vue
Labels: ✨ Feature

#68 [REQ-06-01][FUN-049]프로젝트 관리 메인화면
  src/views/project/ProjectPage.vue
Labels: ✨ Feature

#71 [REQ-04-03][FUN-027] 구성원 상세 페이지
  src/components/member/CommentComponent.vue
  src/components/member/PersonalContractInfoComponent.vue
  src/components/member/PersonalInfoComponent.vue
  src/components/member/PersonalRecordComponent.vue
  src/router/index.js
  src/views/MemberPage.vue
  src/views/member/MemberDetailPage.vue
  src/views/member/MemberPage.vue
Labels: ✨ Feature

#73 [REQ-04-04][FUN-030] 구성원 등록 팝업 화면
  src/router/index.js
  src/views/member/MemberCreatePopup.vue
Labels: ✨ Feature

#74 [REQ-06-02][FUN-051]프로젝트 상세 메인화면
  src/components/project/AmountComponent.vue
  src/components/project/BasicInfoComponent.vue
  src/components/project/MainCompanyComponent.vue
  src/components/project/OrderdingCompanyComponent.vue
  src/router/index.js
  src/views/project/ProjectDetailPage.vue
Labels: ✨ Feature

#78 [COMMON] vue-toastification 설정
  package-lock.json
  package.json
  src/main.js
  src/views/login/FindPasswordPage.vue
  src/views/login/InitializePage.vue
  src/views/login/RegisterPage.vue
Labels: ⚙ Setting

#79 [REQ-07-02][FUN-060] 계약 상세 조회 API 호출
  src/apis/contractService.js
  src/components/common/ModalComponent.vue
  src/components/project/ProgressInfoComponent.vue
  src/views/project/ContractDetailPage.vue
Labels: 🪄 Fix

#80 refactor: api 에러 처리 수정 및 기본 레이아웃 최대 width 수정
  src/adapters/restApiAdapter.js
  src/apis/authService.js
  src/components/common/FooterComponent.vue
  src/components/common/MainHeaderComponent.vue
  src/config/restApiConfig.js
  src/layouts/DefaultLayout.vue
  src/plugins/vuetify.js
  src/views/login/FindPasswordPage.vue
  src/views/login/InitializePage.vue
  src/views/login/RegisterPage.vue
Labels: ✨ Feature

#84 [COMMON] 다이얼로그 구조 개선
  src/App.vue
  src/components/common/DialogComponent.vue
  src/composables/useDialog.js
  src/stores/dialogStore.js
  src/views/project/ContractDetailPage.vue
Labels: 🔨 Refactor

#83 [REQ-02-07][FUN-012] 마이페이지 화면 개발
  src/components/profile/BasicProfileComponent.vue
  src/components/profile/DeleteMemberComponent.vue
  src/components/profile/PasswordChangeComponent.vue
  src/components/profile/ProjectListComponent.vue
  src/components/profile/TeamListComponent.vue
  src/views/ProfilePage.vue
  src/views/login/FindPasswordPage.vue
  src/views/login/InitializePage.vue
  src/views/login/LoginPage.vue
  src/views/login/RegisterPage.vue
  src/views/project/ContractDetailPage.vue
Labels: ✨ Feature

#87 [REQ-07-06][FUN-066] 계약 삭제 처리 확인 팝업 화면
  src/apis/contractService.js
  src/views/project/ContractDetailPage.vue
Labels: ✨ Feature

#94 [REQ-07-02][FUN-060] 계약 수정 API 연동
  src/apis/contractService.js
  src/views/project/ContractDetailPage.vue
Labels: ✨ Feature

#89 [REQ-05-02][FUN-041] 협력사 상세화면 개발
  index.html
  src/apis/partnerService.js
  src/components/partners/AdditionalInfoComponent.vue
  src/components/partners/ContractInfoComponent.vue
  src/components/partners/PartnersInfoComponent.vue
  src/router/index.js
  src/views/partners/PartnersDetailPage.vue
  src/views/partners/PartnersPage.vue
Labels: ✨ Feature

#93 [REQ-02-04] [FUN-002] 로그인 화면
  .github/ISSUE_TEMPLATE/issue-template.md
  src/components/login/LoginComponent.vue
  src/views/login/LoginPage.vue
Labels: ✨ Feature

#95 [COMMON]검색 바 컴포넌트 수정
  src/components/searchbar/SearchBarComponent.vue
Labels: ✨ Feature
